# Generated by Django 2.0.5 on 2018-05-07 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('0', '0~19'), ('20', '20~29'), ('30', '30~39'), ('40', '40~')], max_length=100)),
                ('today_spent_time', models.DurationField()),
                ('now_start_time', models.DateTimeField()),
                ('last_record_time', models.DateTimeField()),
            ],
            options={
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_join', models.DateTimeField(auto_now_add=True)),
                ('catuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat.CatUser')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat.Group')),
            ],
            options={
                'ordering': ('date_join',),
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_start_time', models.DurationField()),
                ('alert_interval', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sun_average', models.DurationField()),
                ('sun_count', models.PositiveIntegerField()),
                ('mon_average', models.DurationField()),
                ('mon_count', models.PositiveIntegerField()),
                ('tue_average', models.DurationField()),
                ('tue_count', models.PositiveIntegerField()),
                ('wed_average', models.DurationField()),
                ('wed_count', models.PositiveIntegerField()),
                ('thu_average', models.DurationField()),
                ('thu_count', models.PositiveIntegerField()),
                ('fri_average', models.DurationField()),
                ('fri_count', models.PositiveIntegerField()),
                ('sat_average', models.DurationField()),
                ('sat_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='cat.Join', to='cat.CatUser'),
        ),
        migrations.AddField(
            model_name='catuser',
            name='setting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cat.Setting'),
        ),
        migrations.AddField(
            model_name='catuser',
            name='timeline',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cat.Timeline'),
        ),
        migrations.AddField(
            model_name='catuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
